apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-cert
  namespace: sock-shop
spec:
  secretName: localhost-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "localhost"
  dnsNames:
    - "localhost"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

